package the_fireplace.frt.recipes;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraftforge.common.brewing.BrewingRecipeRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.OreDictionary;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;
import the_fireplace.frt.FRT;
import the_fireplace.frt.api.ShattererRegistry;
import the_fireplace.frt.tools.MIDLib;

/**
 * @author The_Fireplace
 */
public class VanillaStacks {
    //Vanilla Blocks
    static ItemStack alliumStack = new ItemStack(Blocks.RED_FLOWER, 1, 2);
    static ItemStack azureBluetStack = new ItemStack(Blocks.RED_FLOWER, 1, 3);
    static ItemStack blueOrchidStack = new ItemStack(Blocks.RED_FLOWER, 1, 1);
    static ItemStack bookshelfStack = new ItemStack(Blocks.BOOKSHELF);
    static ItemStack cobbleStack = new ItemStack(Blocks.COBBLESTONE);
    static ItemStack dandelionStack = new ItemStack(Blocks.YELLOW_FLOWER, 1, 0);
    static ItemStack dirtStack = new ItemStack(Blocks.DIRT);
    static ItemStack dirtStack9 = new ItemStack(Blocks.DIRT, 9);
    static ItemStack dispenserStack = new ItemStack(Blocks.DISPENSER);
    static ItemStack glassStack = new ItemStack(Blocks.GLASS);
    static ItemStack glowstoneStack = new ItemStack(Blocks.GLOWSTONE);
    static ItemStack ironTrapdoorStack = new ItemStack(Blocks.IRON_TRAPDOOR);
    static ItemStack lilacStack = new ItemStack(Blocks.DOUBLE_PLANT, 1, 1);
    static ItemStack netherrackStack = new ItemStack(Blocks.NETHERRACK);
    static ItemStack orangeTulipStack = new ItemStack(Blocks.RED_FLOWER, 1, 5);
    static ItemStack oxeyeDaisyStack = new ItemStack(Blocks.RED_FLOWER, 1, 8);
    static ItemStack peonyStack = new ItemStack(Blocks.DOUBLE_PLANT, 1, 5);
    static ItemStack pinkTulipStack = new ItemStack(Blocks.RED_FLOWER, 1, 7);
    static ItemStack poppyStack = new ItemStack(Blocks.RED_FLOWER, 1, 0);
    static ItemStack redTulipStack = new ItemStack(Blocks.RED_FLOWER, 1, 4);
    static ItemStack redstoneBlockStack = new ItemStack(Blocks.REDSTONE_BLOCK);
    static ItemStack roseBushStack = new ItemStack(Blocks.DOUBLE_PLANT, 1, 4);
    static ItemStack sandStack = new ItemStack(Blocks.SAND);
    static ItemStack stainedGlassStack = new ItemStack(Blocks.STAINED_GLASS, 1, OreDictionary.WILDCARD_VALUE);
    static ItemStack stoneStack = new ItemStack(Blocks.STONE);
    static ItemStack stoneSlabStack = new ItemStack(Blocks.STONE_SLAB);
    static ItemStack stoneSlabStack2 = new ItemStack(Blocks.STONE_SLAB, 2);
    static ItemStack sunflowerStack = new ItemStack(Blocks.DOUBLE_PLANT, 1, 0);
    static ItemStack whiteTulipStack = new ItemStack(Blocks.RED_FLOWER, 1, 6);
    static ItemStack woolStack = new ItemStack(Blocks.WOOL, 1, OreDictionary.WILDCARD_VALUE);
    //Vanilla Items
    static ItemStack blazePowderStack = new ItemStack(Items.BLAZE_POWDER);
    static ItemStack blazeRodStack = new ItemStack(Items.BLAZE_ROD);
    static ItemStack boneStack = new ItemStack(Items.BONE);
    static ItemStack boneMealStack = new ItemStack(Items.DYE, 1, 15);
    static ItemStack bottleStack = new ItemStack(Items.GLASS_BOTTLE);
    static ItemStack brickStack = new ItemStack(Items.BRICK);
    static ItemStack cakeStack = new ItemStack(Items.CAKE);
    static ItemStack coalStack = new ItemStack(Items.COAL);
    static ItemStack diamondStack = new ItemStack(Items.DIAMOND);
    static ItemStack dragonBreathStack = new ItemStack(Items.DRAGON_BREATH);
    static ItemStack enderPearlStack = new ItemStack(Items.ENDER_PEARL);
    static ItemStack fireChargeStack = new ItemStack(Items.FIRE_CHARGE);
    static ItemStack flintStack = new ItemStack(Items.FLINT);
    static ItemStack flintAndSteelStack = new ItemStack(Items.FLINT_AND_STEEL);
    static ItemStack glisteringMelonStack = new ItemStack(Items.SPECKLED_MELON);
    static ItemStack glowstoneDustStack = new ItemStack(Items.GLOWSTONE_DUST);
    static ItemStack goldIngotStack = new ItemStack(Items.GOLD_INGOT);
    static ItemStack goldNuggetStack = new ItemStack(Items.GOLD_NUGGET);
    static ItemStack goldenAppleStack = new ItemStack(Items.GOLDEN_APPLE);
    static ItemStack goldenCarrotStack = new ItemStack(Items.GOLDEN_CARROT);
    static ItemStack gunpowderStack = new ItemStack(Items.GUNPOWDER);
    static ItemStack ironStack = new ItemStack(Items.IRON_INGOT);
    static ItemStack leatherStack = new ItemStack(Items.LEATHER);
    static ItemStack magentaDyeStack = new ItemStack(Items.DYE, 1, 13);
    static ItemStack magmaCreamStack = new ItemStack(Items.MAGMA_CREAM);
    static ItemStack orangeDyeStack = new ItemStack(Items.DYE, 1, 14);
    static ItemStack paperStack = new ItemStack(Items.PAPER);
    static ItemStack pinkDyeStack = new ItemStack(Items.DYE, 1, 9);
    static ItemStack redDyeStack = new ItemStack(Items.DYE, 1, 1);
    static ItemStack redMushroomStack = new ItemStack(Blocks.RED_MUSHROOM);
    static ItemStack redstoneStack = new ItemStack(Items.REDSTONE);
    static ItemStack shearsStack = new ItemStack(Items.SHEARS);
    static ItemStack silverDyeStack = new ItemStack(Items.DYE, 1, 7);
    static ItemStack skyDyeStack = new ItemStack(Items.DYE, 1, 12);
    static ItemStack slimeballStack = new ItemStack(Items.SLIME_BALL);
    static ItemStack stringStack = new ItemStack(Items.STRING);
    static ItemStack sugarStack = new ItemStack(Items.SUGAR);
    static ItemStack sugarCaneStack = new ItemStack(Items.REEDS);
    static ItemStack yellowDyeStack = new ItemStack(Items.DYE, 1, 11);
    //Custom Blocks
    static ItemStack blackScreenStack = new ItemStack(FRT.black_screen);
    static ItemStack blazeCakeStack = new ItemStack(FRT.blaze_cake);
    static ItemStack blueScreenStack = new ItemStack(FRT.blue_screen);
    static ItemStack brownScreenStack = new ItemStack(FRT.brown_screen);
    static ItemStack candleStack = new ItemStack(FRT.candle);
    static ItemStack candlePlateStack = new ItemStack(FRT.candle_with_base);
    static ItemStack chargedCoalBlockStack = new ItemStack(FRT.charged_coal_block);
    static ItemStack compactBookshelfStack = new ItemStack(FRT.compact_bookshelf);
    static ItemStack compactDirtStack = new ItemStack(FRT.compact_dirt);
    static ItemStack cyanScreenStack = new ItemStack(FRT.cyan_screen);
    static ItemStack darkTanScreenStack = new ItemStack(FRT.dark_tan_screen);
    static ItemStack destabilizedCoalBlockStack = new ItemStack(FRT.destabilized_coal_block);
    static ItemStack fireplaceBottomStack2 = new ItemStack(FRT.fireplace_bottom, 2);
    static ItemStack fossilStack = new ItemStack(FRT.fossil);
    static ItemStack greenScreenStack = new ItemStack(FRT.green_screen);
    static ItemStack greyScreenStack = new ItemStack(FRT.grey_screen);
    static ItemStack insaneDispenserStack = new ItemStack(FRT.insane_dispenser);
    static ItemStack lightOrangeScreenStack = new ItemStack(FRT.light_orange_screen);
    static ItemStack lightTanScreenStack = new ItemStack(FRT.light_tan_screen);
    static ItemStack limeScreenStack = new ItemStack(FRT.lime_screen);
    static ItemStack magentaScreenStack = new ItemStack(FRT.magenta_screen);
    static ItemStack orangeScreenStack = new ItemStack(FRT.orange_screen);
    static ItemStack pinkScreenStack = new ItemStack(FRT.pink_screen);
    static ItemStack polishedStoneStack = new ItemStack(FRT.polished_stone);
    static ItemStack polishedStoneStack2 = new ItemStack(FRT.polished_stone, 2);
    static ItemStack popFurnaceStack = new ItemStack(FRT.pop_furnace);
    static ItemStack purpleScreenStack = new ItemStack(FRT.purple_screen);
    static ItemStack quadDispenserStack = new ItemStack(FRT.quad_dispenser);
    static ItemStack redScreenStack = new ItemStack(FRT.red_screen);
    static ItemStack refinedCoalBlockStack = new ItemStack(FRT.refined_coal_block);
    static ItemStack restabilizedCoalBlockStack = new ItemStack(FRT.restabilized_coal_block);
    static ItemStack shellCoreStack = new ItemStack(FRT.shell_core);
    static ItemStack silverScreenStack = new ItemStack(FRT.silver_screen);
    static ItemStack skyScreenStack = new ItemStack(FRT.sky_screen);
    static ItemStack waxBlockStack = new ItemStack(FRT.wax_deposit);
    static ItemStack whiteScreenStack = new ItemStack(FRT.white_screen);
    static ItemStack yellowScreenStack = new ItemStack(FRT.yellow_screen);
    //Custom Items
    static ItemStack chargedCoalStack = new ItemStack(FRT.charged_coal);
    static ItemStack chargedCoalStack8 = new ItemStack(FRT.charged_coal, 8);
    static ItemStack chargedCoalStack9 = new ItemStack(FRT.charged_coal, 9);
    static ItemStack coalGunStack = new ItemStack(FRT.coal_gun);
    static ItemStack coalGunBarrelStack = new ItemStack(FRT.coal_gun_barrel);
    static ItemStack coalGunStockStack = new ItemStack(FRT.coal_gun_stock);
    static ItemStack destabilizedCoalStack = new ItemStack(FRT.destabilized_coal);
    static ItemStack destabilizedCoalStack6 = new ItemStack(FRT.destabilized_coal, 6);
    static ItemStack destabilizedCoalStack9 = new ItemStack(FRT.destabilized_coal, 9);
    static ItemStack diamondPaxelStack = new ItemStack(FRT.diamond_paxel);
    static ItemStack firestarterSubstituteStack = new ItemStack(FRT.firestarter_substitute);
    static ItemStack goldPaxelStack = new ItemStack(FRT.gold_paxel);
    static ItemStack gunpowderSubstituteStack = new ItemStack(FRT.gunpowder_substitute);
    static ItemStack hallucinationGogglesStack = new ItemStack(FRT.hallucination_goggles);
    static ItemStack ironPaxelStack = new ItemStack(FRT.iron_paxel);
    static ItemStack kineticPearlStack = new ItemStack(FRT.kinetic_pearl);
    static ItemStack leafcutterStack = new ItemStack(FRT.leafcutter);
    static ItemStack obsidianToolStack = new ItemStack(FRT.obsidian_tool);
    static ItemStack refinedCoalStack = new ItemStack(FRT.refined_coal);
    static ItemStack refinedCoalStack9 = new ItemStack(FRT.refined_coal, 9);
    static ItemStack restabilizedCoalStack = new ItemStack(FRT.restabilized_coal);
    static ItemStack restabilizedCoalStack8 = new ItemStack(FRT.restabilized_coal, 8);
    static ItemStack restabilizedCoalStack9 = new ItemStack(FRT.restabilized_coal, 9);
    static ItemStack stonePaxelStack = new ItemStack(FRT.stone_paxel);
    static ItemStack waxStack = new ItemStack(FRT.wax);
    static ItemStack waxStack4 = new ItemStack(FRT.wax, 4);
    static ItemStack woodPaxelStack = new ItemStack(FRT.wood_paxel);

    /**
     * This is where recipes that, even if additional recipes are added, will not be removed. Call in all {@link IRecipeRegister#registerRecipes()}.
     */
    public static void registerConstantRecipes() {
        shaped(waxBlockStack, "ww", "ww", 'w', waxStack);
        shaped(coalGunStack, "xxy", 'x', coalGunBarrelStack, 'y', coalGunStockStack);
        shaped(polishedStoneStack2, " s ", "s s", " s ", 's', stoneSlabStack);
        shaped(blazeCakeStack, "m", "c", 'm', magmaCreamStack, 'c', cakeStack);
        shaped(blazeCakeStack, "p", "s", "c", 'p', blazePowderStack, 's', slimeballStack, 'c', cakeStack);
        shaped(chargedCoalBlockStack, "ccc", "ccc", "ccc", 'c', chargedCoalStack);
        shaped(destabilizedCoalBlockStack, "ccc", "ccc", "ccc", 'c', destabilizedCoalStack);
        shaped(restabilizedCoalBlockStack, "ccc", "ccc", "ccc", 'c', restabilizedCoalStack);
        shaped(refinedCoalBlockStack, "ccc", "ccc", "ccc", 'c', refinedCoalStack);
        shaped(chargedCoalStack8, "ccc", "crc", "ccc", 'c', coalStack, 'r', redstoneStack);
        shaped(fireplaceBottomStack2, "bbb", "bnb", "bbb", 'b', brickStack, 'n', netherrackStack);
        shaped(whiteScreenStack, " p ", "pwp", " p ", 'p', paperStack, 'w', woolStack);
        shaped(destabilizedCoalStack6, "ccc", "ggg", "ccc", 'c', chargedCoalStack, 'g', gunpowderStack);
        shaped(restabilizedCoalStack8, "ccc", "csc", "ccc", 'c', destabilizedCoalStack, 's', slimeballStack);
        shaped(quadDispenserStack, "dd", "dd", 'd', dispenserStack);
        shaped(insaneDispenserStack, "dd", "dd", 'd', quadDispenserStack);
        shaped(bookshelfStack, "www", "bbb", "www", 'w', "plankWood", 'b', "book");
        shaped(candleStack, "s", "w", "w", 's', stringStack, 'w', waxStack);
        shaped(candlePlateStack, " c ", "nnn", 'c', candleStack, 'n', "nuggetGold");
        shaped(popFurnaceStack, "bib", "btb", "bib", 'b', "blockIron", 't', ironTrapdoorStack, 'i', "ingotIron");
        shaped(obsidianToolStack, "dpd", "dsd", " s ", 'd', "gemDiamond", 'p', "gemPrismarine", 's', "stickWood");
        shaped(shellCoreStack, "grg", "rer", "grg", 'g', "blockGold", 'r', redstoneBlockStack, 'e', enderPearlStack);
        shapeless(waxStack4, waxBlockStack);
        shapeless(dirtStack9, compactDirtStack);
        shapeless(chargedCoalStack9, chargedCoalBlockStack);
        shapeless(destabilizedCoalStack9, destabilizedCoalBlockStack);
        shapeless(restabilizedCoalStack9, restabilizedCoalBlockStack);
        shapeless(refinedCoalStack9, refinedCoalBlockStack);
        shapeless(stoneSlabStack2, polishedStoneStack);
        GameRegistry.addSmelting(restabilizedCoalStack, refinedCoalStack, 0.05F);
        NBTTagCompound potionS = new NBTTagCompound();
        NBTTagCompound potionL = new NBTTagCompound();
        NBTTagCompound potionA = new NBTTagCompound();
        potionS.setString("Potion", "frt:hallucination");
        potionL.setString("Potion", "frt:long_hallucination");
        potionA.setString("Potion", "minecraft:awkward");
        ItemStack hallucinationPotionStackS = new ItemStack(Items.POTIONITEM);
        hallucinationPotionStackS.setTagCompound(potionS);
        ItemStack hallucinationPotionStackL = new ItemStack(Items.POTIONITEM);
        hallucinationPotionStackL.setTagCompound(potionL);
        ItemStack hallucinationPotionStackSS = new ItemStack(Items.SPLASH_POTION);
        hallucinationPotionStackSS.setTagCompound(potionS);
        ItemStack hallucinationPotionStackSL = new ItemStack(Items.SPLASH_POTION);
        hallucinationPotionStackSL.setTagCompound(potionL);
        ItemStack hallucinationPotionStackLS = new ItemStack(Items.LINGERING_POTION);
        hallucinationPotionStackLS.setTagCompound(potionS);
        ItemStack hallucinationPotionStackLL = new ItemStack(Items.LINGERING_POTION);
        hallucinationPotionStackLL.setTagCompound(potionL);
        ItemStack awkwardPotionStack = new ItemStack(Items.POTIONITEM);
        awkwardPotionStack.setTagCompound(potionA);
        ItemStack awkwardSplashPotionStack = new ItemStack(Items.SPLASH_POTION);
        awkwardSplashPotionStack.setTagCompound(potionA);
        ItemStack awkwardLingeringPotionStack = new ItemStack(Items.LINGERING_POTION);
        awkwardLingeringPotionStack.setTagCompound(potionA);
        BrewingRecipeRegistry.addRecipe(awkwardPotionStack, redMushroomStack, hallucinationPotionStackS);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackS, redstoneStack, hallucinationPotionStackL);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackS, gunpowderStack, hallucinationPotionStackSS);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackL, gunpowderStack, hallucinationPotionStackSL);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackSS, redstoneStack, hallucinationPotionStackSL);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackSS, dragonBreathStack, hallucinationPotionStackLS);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackSL, dragonBreathStack, hallucinationPotionStackLL);
        BrewingRecipeRegistry.addRecipe(hallucinationPotionStackLS, redstoneStack, hallucinationPotionStackLL);
        BrewingRecipeRegistry.addRecipe(awkwardLingeringPotionStack, redMushroomStack, hallucinationPotionStackLS);
        BrewingRecipeRegistry.addRecipe(awkwardSplashPotionStack, redMushroomStack, hallucinationPotionStackSS);
        shaped(hallucinationGogglesStack, "l l", "gpg", 'l', leatherStack, 'g', "paneGlass", 'p', hallucinationPotionStackS);
        shaped(woodPaxelStack, "www", " w ", " s ", 'w', "plankWood", 's', "stickWood");
        shaped(ironPaxelStack, "www", " w ", " s ", 'w', ironStack, 's', "stickWood");
        shaped(goldPaxelStack, "www", " w ", " s ", 'w', goldIngotStack, 's', "stickWood");
        shaped(diamondPaxelStack, "www", " w ", " s ", 'w', diamondStack, 's', "stickWood");
        shaped(leafcutterStack, " s ", "t t", "t t", 's', shearsStack, 't', "stickWood");
        shaped(kineticPearlStack, " g ", "geg", " g ", 'g', "nuggetGold", 'e', enderPearlStack);
        shapeless(whiteScreenStack, "screen", "dyeWhite", "dyeWhite");
        shapeless(redScreenStack, "screen", "dyeRed", "dyeRed");
        shapeless(blueScreenStack, "screen", "dyeBlue", "dyeBlue");
        shapeless(orangeScreenStack, "screen", "dyeOrange", "dyeOrange");
        shapeless(orangeScreenStack, "screen", "dyeYellow", "dyeRed");
        shapeless(yellowScreenStack, "screen", "dyeYellow", "dyeYellow");
        shapeless(greenScreenStack, "screen", "dyeGreen", "dyeGreen");
        shapeless(lightTanScreenStack, "screen", "dyeBrown", "dyeWhite", "dyeWhite");
        shapeless(lightOrangeScreenStack, "screen", "dyeOrange", "dyeWhite");
        shapeless(brownScreenStack, "screen", "dyeBrown", "dyeBrown");
        shapeless(blackScreenStack, "screen", "dyeBlack", "dyeBlack");
        shapeless(purpleScreenStack, "screen", "dyePurple", "dyePurple");
        shapeless(purpleScreenStack, "screen", "dyeRed", "dyeBlue");
        shapeless(limeScreenStack, "screen", "dyeLime", "dyeLime");
        shapeless(limeScreenStack, "screen", "dyeWhite", "dyeGreen");
        shapeless(cyanScreenStack, "screen", "dyeCyan", "dyeCyan");
        shapeless(cyanScreenStack, "screen", "dyeGreen", "dyeBlue");
        shapeless(silverScreenStack, "screen", "dyeLightGray", "dyeLightGray");
        shapeless(greyScreenStack, "screen", "dyeGray", "dyeGray");
        shapeless(greyScreenStack, "screen", "dyeWhite", "dyeBlack");
        shapeless(pinkScreenStack, "screen", "dyePink", "dyePink");
        shapeless(pinkScreenStack, "screen", "dyeWhite", "dyeRed");
        shapeless(skyScreenStack, "screen", "dyeLightBlue", "dyeLightBlue");
        shapeless(skyScreenStack, "screen", "dyeWhite", "dyeBlue");
        shapeless(magentaScreenStack, "screen", "dyeMagenta", "dyeMagenta");
        shapeless(darkTanScreenStack, "screen", "dyeBrown", "dyeWhite");
        shapeless(blackScreenStack, whiteScreenStack, "dyeBlack");
        shapeless(redScreenStack, whiteScreenStack, "dyeRed");
        shapeless(orangeScreenStack, whiteScreenStack, "dyeOrange");
        shapeless(yellowScreenStack, whiteScreenStack, "dyeYellow");
        shapeless(greenScreenStack, whiteScreenStack, "dyeGreen");
        shapeless(limeScreenStack, whiteScreenStack, "dyeLime");
        shapeless(blueScreenStack, whiteScreenStack, "dyeBlue");
        shapeless(cyanScreenStack, whiteScreenStack, "dyeCyan");
        shapeless(purpleScreenStack, whiteScreenStack, "dyePurple");
        shapeless(pinkScreenStack, whiteScreenStack, "dyePink");
        shapeless(brownScreenStack, whiteScreenStack, "dyeBrown");
        shapeless(greyScreenStack, whiteScreenStack, "dyeGray");
        shapeless(silverScreenStack, whiteScreenStack, "dyeLightGray");
        shapeless(skyScreenStack, whiteScreenStack, "dyeLightBlue");
        shapeless(magentaScreenStack, whiteScreenStack, "dyeMagenta");
        ShattererRegistry.registerGunpowder(gunpowderStack, gunpowderSubstituteStack);
        ShattererRegistry.registerFirestarter(flintAndSteelStack, fireChargeStack, firestarterSubstituteStack);
        ShattererRegistry.registerPopFurnaceRecipe(glassStack, sandStack, 1);
        ShattererRegistry.registerPopFurnaceRecipe(stainedGlassStack, sandStack, 1);
        ShattererRegistry.registerPopFurnaceRecipe(bottleStack, sandStack, 1);
        ShattererRegistry.registerPopFurnaceRecipe(sugarCaneStack, sugarStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(glowstoneStack, glowstoneDustStack, 4);
        ShattererRegistry.registerPopFurnaceRecipe(boneStack, boneMealStack, 4);
        ShattererRegistry.registerPopFurnaceRecipe(blazeRodStack, blazePowderStack, 4);
        ShattererRegistry.registerPopFurnaceRecipe(dandelionStack, yellowDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(poppyStack, redDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(blueOrchidStack, skyDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(alliumStack, magentaDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(azureBluetStack, silverDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(redTulipStack, redDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(orangeTulipStack, orangeDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(whiteTulipStack, silverDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(pinkTulipStack, pinkDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(oxeyeDaisyStack, silverDyeStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(sunflowerStack, yellowDyeStack, 3);
        ShattererRegistry.registerPopFurnaceRecipe(lilacStack, magentaDyeStack, 3);
        ShattererRegistry.registerPopFurnaceRecipe(roseBushStack, redDyeStack, 3);
        ShattererRegistry.registerPopFurnaceRecipe(peonyStack, pinkDyeStack, 3);
        ShattererRegistry.registerPopFurnaceRecipe(candleStack, waxStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(candlePlateStack, waxStack, 2);
        ShattererRegistry.registerPopFurnaceRecipe(fossilStack, boneMealStack, 6);
        shaped(coalGunBarrelStack, "fff", "   ", "fff", 'f', flintStack);
        shaped(coalGunStockStack, "fff", "s f", "fff", 'f', flintStack, 's', flintAndSteelStack);
        shaped(compactDirtStack, "ddd", "ddd", "ddd", 'd', dirtStack);
        shaped(compactBookshelfStack, "bbb", 'b', bookshelfStack);
        //Recipes that change with certain mods installed, which don't require different classes
        if (MIDLib.hasRealStoneTools()) {
            shaped(stonePaxelStack, "www", " w ", " s ", 'w', stoneStack, 's', "stickWood");
        } else {
            shaped(stonePaxelStack, "www", " w ", " s ", 'w', cobbleStack, 's', "stickWood");
        }
    }

    public static void shapeless(ItemStack is, Object... args) {
        GameRegistry.addRecipe(new ShapelessOreRecipe(is, args));
    }

    public static void shaped(ItemStack is, Object... args) {
        GameRegistry.addRecipe(new ShapedOreRecipe(is, args));
    }
}
